<?php

/**
 * @file
 * Contains jisc_ci.module.
 */

declare(strict_types=0);

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 *
 * @param $route_name
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 *
 * @return string
 */
function jisc_ci_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        // Main module help for the jisc_ci module.
        case 'help.page.jisc_ci':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Jisc CI') . '</p>';
            return $output;

        default:
    }
}
